# Generated by Django 2.2 on 2019-04-22 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S3DataUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_name', models.CharField(max_length=255)),
                ('total_data_upload', models.IntegerField(blank=True, default=0)),
                ('total_data_download', models.IntegerField(blank=True, default=0)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('modified_tme', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='s3datausage',
            index=models.Index(fields=['portal_name'], name='product_s3d_portal__dbaa27_idx'),
        ),
        migrations.AddIndex(
            model_name='s3datausage',
            index=models.Index(fields=['from_date'], name='product_s3d_from_da_4f27e9_idx'),
        ),
    ]
