# Generated by Django 2.2 on 2019-04-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='s3datausage',
            index=models.Index(fields=['to_date'], name='product_s3d_to_date_1ba7f5_idx'),
        ),
    ]
