# Generated by Django 2.2 on 2019-04-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_name', models.CharField(max_length=255)),
                ('access_key', models.CharField(max_length=255)),
                ('total_device', models.IntegerField(blank=True, default=0)),
                ('data_allowed_per_device', models.IntegerField(blank=True, default=250)),
            ],
        ),
    ]
