# Generated by Django 2.2 on 2019-05-15 10:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20190503_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaldetails',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 10, 17, 45, 936347, tzinfo=utc)),
        ),
    ]
