# Generated by Django 2.2 on 2019-05-15 10:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_auto_20190515_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaldetails',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 10, 44, 5, 921263, tzinfo=utc)),
        ),
    ]
