# Generated by Django 2.2 on 2019-05-16 06:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_auto_20190516_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaldetails',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 6, 18, 9, 332597, tzinfo=utc)),
        ),
    ]
